// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// treeowen_ping
SEXP treeowen_ping();
RcppExport SEXP _treeowen_treeowen_ping() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(treeowen_ping());
    return rcpp_result_gen;
END_RCPP
}
// prepare_trees_xptr
SEXP prepare_trees_xptr(List trees_list);
RcppExport SEXP _treeowen_prepare_trees_xptr(SEXP trees_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type trees_list(trees_listSEXP);
    rcpp_result_gen = Rcpp::wrap(prepare_trees_xptr(trees_list));
    return rcpp_result_gen;
END_RCPP
}
// popcount_table_cpp
IntegerVector popcount_table_cpp(int max_mask);
RcppExport SEXP _treeowen_popcount_table_cpp(SEXP max_maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type max_mask(max_maskSEXP);
    rcpp_result_gen = Rcpp::wrap(popcount_table_cpp(max_mask));
    return rcpp_result_gen;
END_RCPP
}
// shapley_weights_cpp
NumericVector shapley_weights_cpp(int m);
RcppExport SEXP _treeowen_shapley_weights_cpp(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(shapley_weights_cpp(m));
    return rcpp_result_gen;
END_RCPP
}
// eval_v_knownset_cpp
double eval_v_knownset_cpp(SEXP trees_xptr, NumericVector x_row, IntegerVector known_cols, int maxj);
RcppExport SEXP _treeowen_eval_v_knownset_cpp(SEXP trees_xptrSEXP, SEXP x_rowSEXP, SEXP known_colsSEXP, SEXP maxjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type trees_xptr(trees_xptrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_row(x_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type known_cols(known_colsSEXP);
    Rcpp::traits::input_parameter< int >::type maxj(maxjSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_v_knownset_cpp(trees_xptr, x_row, known_cols, maxj));
    return rcpp_result_gen;
END_RCPP
}
// inner_shapley_enum_one_group_cpp
NumericVector inner_shapley_enum_one_group_cpp(SEXP trees_xptr, NumericVector x_row, int maxj, IntegerVector group_feats_g, List group_feats_others, int K, int p);
RcppExport SEXP _treeowen_inner_shapley_enum_one_group_cpp(SEXP trees_xptrSEXP, SEXP x_rowSEXP, SEXP maxjSEXP, SEXP group_feats_gSEXP, SEXP group_feats_othersSEXP, SEXP KSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type trees_xptr(trees_xptrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_row(x_rowSEXP);
    Rcpp::traits::input_parameter< int >::type maxj(maxjSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_feats_g(group_feats_gSEXP);
    Rcpp::traits::input_parameter< List >::type group_feats_others(group_feats_othersSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(inner_shapley_enum_one_group_cpp(trees_xptr, x_row, maxj, group_feats_g, group_feats_others, K, p));
    return rcpp_result_gen;
END_RCPP
}
// inner_shapley_exact_cpp
NumericVector inner_shapley_exact_cpp(SEXP trees_xptr, NumericVector x_row, IntegerVector feats_g, IntegerVector outer_known_cols, int maxj, int p, int chunk_size);
RcppExport SEXP _treeowen_inner_shapley_exact_cpp(SEXP trees_xptrSEXP, SEXP x_rowSEXP, SEXP feats_gSEXP, SEXP outer_known_colsSEXP, SEXP maxjSEXP, SEXP pSEXP, SEXP chunk_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type trees_xptr(trees_xptrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_row(x_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type feats_g(feats_gSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type outer_known_cols(outer_known_colsSEXP);
    Rcpp::traits::input_parameter< int >::type maxj(maxjSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(inner_shapley_exact_cpp(trees_xptr, x_row, feats_g, outer_known_cols, maxj, p, chunk_size));
    return rcpp_result_gen;
END_RCPP
}
// inner_mc_perm_cpp
NumericVector inner_mc_perm_cpp(SEXP trees_xptr, NumericVector x_row, IntegerVector feats_g, IntegerVector outer_known_cols, int maxj, int p, int n_perm, bool antithetic, double target_se, int min_perm);
RcppExport SEXP _treeowen_inner_mc_perm_cpp(SEXP trees_xptrSEXP, SEXP x_rowSEXP, SEXP feats_gSEXP, SEXP outer_known_colsSEXP, SEXP maxjSEXP, SEXP pSEXP, SEXP n_permSEXP, SEXP antitheticSEXP, SEXP target_seSEXP, SEXP min_permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type trees_xptr(trees_xptrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_row(x_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type feats_g(feats_gSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type outer_known_cols(outer_known_colsSEXP);
    Rcpp::traits::input_parameter< int >::type maxj(maxjSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< bool >::type antithetic(antitheticSEXP);
    Rcpp::traits::input_parameter< double >::type target_se(target_seSEXP);
    Rcpp::traits::input_parameter< int >::type min_perm(min_permSEXP);
    rcpp_result_gen = Rcpp::wrap(inner_mc_perm_cpp(trees_xptr, x_row, feats_g, outer_known_cols, maxj, p, n_perm, antithetic, target_se, min_perm));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_treeowen_treeowen_ping", (DL_FUNC) &_treeowen_treeowen_ping, 0},
    {"treeowen_ping",            (DL_FUNC) &_treeowen_treeowen_ping, 0},
    {"_treeowen_prepare_trees_xptr", (DL_FUNC) &_treeowen_prepare_trees_xptr, 1},
    {"_treeowen_popcount_table_cpp", (DL_FUNC) &_treeowen_popcount_table_cpp, 1},
    {"_treeowen_shapley_weights_cpp", (DL_FUNC) &_treeowen_shapley_weights_cpp, 1},
    {"_treeowen_eval_v_knownset_cpp", (DL_FUNC) &_treeowen_eval_v_knownset_cpp, 4},
    {"_treeowen_inner_shapley_enum_one_group_cpp", (DL_FUNC) &_treeowen_inner_shapley_enum_one_group_cpp, 7},
    {"_treeowen_inner_shapley_exact_cpp", (DL_FUNC) &_treeowen_inner_shapley_exact_cpp, 7},
    {"_treeowen_inner_mc_perm_cpp", (DL_FUNC) &_treeowen_inner_mc_perm_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_treeowen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, TRUE);
}
