# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

treeowen_ping <- function() {
    .Call(`_treeowen_treeowen_ping`)
}

prepare_trees_xptr <- function(trees_list) {
    .Call(`_treeowen_prepare_trees_xptr`, trees_list)
}

popcount_table_cpp <- function(max_mask) {
    .Call(`_treeowen_popcount_table_cpp`, max_mask)
}

shapley_weights_cpp <- function(m) {
    .Call(`_treeowen_shapley_weights_cpp`, m)
}

eval_v_knownset_cpp <- function(trees_xptr, x_row, known_cols, maxj) {
    .Call(`_treeowen_eval_v_knownset_cpp`, trees_xptr, x_row, known_cols, maxj)
}

inner_shapley_enum_one_group_cpp <- function(trees_xptr, x_row, maxj, group_feats_g, group_feats_others, K, p) {
    .Call(`_treeowen_inner_shapley_enum_one_group_cpp`, trees_xptr, x_row, maxj, group_feats_g, group_feats_others, K, p)
}

inner_shapley_exact_cpp <- function(trees_xptr, x_row, feats_g, outer_known_cols, maxj, p, chunk_size) {
    .Call(`_treeowen_inner_shapley_exact_cpp`, trees_xptr, x_row, feats_g, outer_known_cols, maxj, p, chunk_size)
}

inner_mc_perm_cpp <- function(trees_xptr, x_row, feats_g, outer_known_cols, maxj, p, n_perm, antithetic, target_se, min_perm) {
    .Call(`_treeowen_inner_mc_perm_cpp`, trees_xptr, x_row, feats_g, outer_known_cols, maxj, p, n_perm, antithetic, target_se, min_perm)
}
